// This source code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © thedigitalchief
// @version=5

indicator("Bitcoin EMA + Bollinger Bands Algorithm Script", overlay = true) //chart line is now over the candle sticks

fast = input.int(10, minval = 1, title = "Fast EMA") //EMA = Exponential Moving Average
slow = input.int(30, minval = 1, title = "Slow EMA")

fastEMA = ta.ema(close, fast) //function "ema" return EMA of closing prices of certain number of days
slowEMA = ta.ema(close, slow)

buy = ta.crossover(fastEMA, slowEMA) //buy and sell function parameters
sell = ta.crossunder(fastEMA, slowEMA)

if sell
    lbl = label.new(bar_index, low, "Sell")
    label.set_color(lbl, color.red)
    label.set_yloc(lbl, yloc.abovebar)
    label.set_style(lbl, label.style_label_down)
    
if buy
    buy_label = label.new(bar_index, low, "Buy")
    label.set_color(buy_label, color.green)
    label.set_yloc(buy_label, yloc.belowbar)
    label.set_style(buy_label, label.style_label_up)

plot(fastEMA, "Fast Ema", color = color.blue, linewidth = 3) //graphing fast ema
plot(slowEMA, "Slow Ema", color = color.orange, linewidth = 3) //graphing slow ema


// RSI and MFI implementation
source = hlc3 //HLC = High, Low, Close and /3 divides the result by 3 to give average

length = input.int(14, minval=1), mult = input.float(2.0, minval=0.001, maxval=50)
DrawRSI_f=input.bool(false, title="Draw RSI?", type=bool)
DrawMFI_f=input.bool(true, title="Draw MFI?", type=bool)
HighlightBreaches=input.bool(true, title="Highlight Oversold/Overbought?", type=bool)

DrawMFI = (not DrawMFI_f) and (not DrawRSI_f) ? true : DrawMFI_f
DrawRSI = (DrawMFI_f and DrawRSI_f) ? false : DrawRSI_f

// RSI = Relative Strength Index
rsi_s = DrawRSI ? ta.rsi(source, length) : na
plot(DrawRSI ? rsi_s : na, color= color.maroon, linewidth=2)

// MFI = Money Flow Index
upper_s = DrawMFI ? math.sum(volume * (ta.change(source) <= 0 ? 0 : source), length) : na
lower_s = DrawMFI ? math.sum(volume * (ta.change(source) >= 0 ? 0 : source), length) : na

// graphing MFI
mf = DrawMFI ? ta.rsi(upper_s, lower_s) : na
plot(DrawMFI ? mf : na, color=color.green, linewidth=2)



// graphing Bollinger Bands on indices
bb_s = DrawRSI ? rsi_s : DrawMFI ? mf : na
basis = ta.sma(bb_s, length)
dev = mult * ta.stdev(bb_s, length)

upper = basis + dev
lower = basis - dev

plot(basis, color= color.red)
p1 = plot(upper, color= color.blue)
p2 = plot(lower, color= color.blue)
fill(p1,p2, color.blue)
b_color = (bb_s > upper) ? color.red : (bb_s < lower) ? color.green : na
bgcolor(HighlightBreaches ? b_color : na)
