// This source code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © thedigitalchief

// RSI/MFI with Bollinger Bands

indicator(title = "RSI/MFI with Volatility Bands [LazyBear]", shorttitle="SI+Bands [LB]")

source = hlc3

length = input.int(14, minval=1), mult = input.float(2.0, minval=0.001, maxval=50)
DrawRSI_f=input.bool(false, title="Draw RSI?", type=bool)
DrawMFI_f=input.bool(true, title="Draw MFI?", type=bool)
HighlightBreaches=input.bool(true, title="Highlight Oversold/Overbought?", type=bool)

DrawMFI = (not DrawMFI_f) and (not DrawRSI_f) ? true : DrawMFI_f
DrawRSI = (DrawMFI_f and DrawRSI_f) ? false : DrawRSI_f

// RSI
rsi_s = DrawRSI ? ta.rsi(source, length) : na
plot(DrawRSI ? rsi_s : na, color= color.maroon, linewidth=2)

// MFI
upper_s = DrawMFI ? math.sum(volume * (ta.change(source) <= 0 ? 0 : source), length) : na
lower_s = DrawMFI ? math.sum(volume * (ta.change(source) >= 0 ? 0 : source), length) : na

mf = DrawMFI ? ta.rsi(upper_s, lower_s) : na
plot(DrawMFI ? mf : na, color=color.green, linewidth=2)


// Graphing Bollinger Bands on indices
bb_s = DrawRSI ? rsi_s : DrawMFI ? mf : na
basis = ta.sma(bb_s, length)
dev = mult * ta.stdev(bb_s, length)
upper = basis + dev
lower = basis - dev
plot(basis, color= color.red)
p1 = plot(upper, color= color.blue)
p2 = plot(lower, color= color.blue)
fill(p1,p2, color.blue)

b_color = (bb_s > upper) ? color.red : (bb_s < lower) ? color.green : na
bgcolor(HighlightBreaches ? b_color : na)
